version: "3.9"

services:
  ci-cd-helper:
    image: ci-cd-helper
    container_name: ci-cd-helper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./settings.json:/app/settings.json"
